version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.app
    container_name: partymachine_app
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/localhost/htdocs/app
    ports:
      - 17280:8080
    entrypoint: /docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: mysql:5.7.40
    platform: linux/x86_64
    container_name: partymachine_db
    volumes:
      - ./.docker/configs/my.cnf:/etc/my.cnf
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root